[package]
name = "cic_bitboard"
version = "0.1.0"
edition = "2021"
description = "simple bitboard implementation"
license = "MIT"

[dependencies]
tracing-core = "0.1.32"
rand = "0.8.4"
rayon = "1.10.0"
