[package]
name = "CIC-bitboard"
version = "0.1.0"
edition = "2021"
description = "simple bitboard implementation"
license = "MIT"

[dependencies]
tracing-core = "0.1.32"

[lib]
name = "chess_game"
crate-type = ["lib"]
