name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd chess_game/src; cargo build --verbose
    - name: Lint
      run: cd chess_game/src; cargo clippy
    - name: Run tests
      run: cd chess_game/src; cargo test --verbose
